baseURL = 'https://blog.nativi.sh/'
languageCode = 'en-us'
title = 'Nativish Blog'
theme = "nativish-theme"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
paginate = 10  
paginatePath = "page" 


[languages]
[languages.en]
  contentDir = 'content/en'
  languageCode = 'en-US'
  languageDirection = 'ltr'
  languageName = "English"
  weight = 1
  [languages.en.permalinks]
  [languages.en.permalinks.page]
    posts = '/:slug/'
[languages.fr]
  contentDir = 'content/fr'
  languageCode = 'fr-FR'
  languageDirection = 'ltr'
  languageName = "Français"
  weight = 2
  [languages.fr.permalinks]
  [languages.fr.permalinks.page]
    posts = '/:slug/'

[taxonomies]
  category = 'categories'
  target_language = 'target_languages'
  tag = 'tags'

[imaging]
  bgColor = '#ffffff'
  quality = 100
