baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Nativish Blog'
theme = "nativish-theme"
defaultContentLanguage = "en"


[languages]
[languages.en]
  languageName = "English"
  weight = 1
