baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Nativish Blog'
theme = "nativish-theme"
defaultContentLanguage = "en"


[languages]
[languages.en]
  languageName = "English"
  weight = 1

[taxonomies]
  category = 'categories'
  target_language = 'target_languages'
  tag = 'tags'
